In [2]:
import pandas as pd; import numpy as np;

## Veriyi Gruplara Ayırma

- Veriyi belli aralıkta gruplara ayırmak için `cut` metodu kullanılır.
- `cut` metodu ile aralıklara bölmek için birden fazla yol vardır. İlk seçenek aralıkların bizim tarafımızdan belirlenmesidir. Kullanımı:
    aralik = [20,40,60,80,100]
    pd.cut(<veri_seti>, aralik)
  şeklindedir. 
- Ek olarak aralıklara isim verilebilir. Bunun için aralıkların isminin verildiği bir dizi oluşturularak metota `labels = <aralık_isimleri>`şeklinde parametre olarak verilmelidir. 
- Bir diğer yöntem ise belirli sayıda aralığa bölmesi istenilebilir. Bunun için bir önceki seçenekte `aralik` olarak verilen parametre yerine ne kadar aralığa bölünmesini istiyorsak sayısını parametre olarak verilir. Aralıklar içerdeki max ve min değere göre otamatik olarak bölünür.
- Son seçenek ise eleman sayısını eşit aralıklara bölmek için kullanılır. Örneğin 100 örnekli bir veri seti var ve bunu 25 elemanlı 4 parçaya ayırmak istenirse `qcut` metotu kullanılır. Kullanımı:
    pd.qcut(<veri_seti>,4)
  şeklindedir.
  4 yerine verdiğimiz sayıya göre eleman sayısı eşit olacak şekilde veriyi parçalar.

In [6]:
nt = [30,80,40,90,60,45,95,75,55,100,65,85]

In [15]:
aralik = [20,40,60,80,100]

In [16]:
puan = pd.cut(nt,aralık)
puan

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [17]:
puan.codes

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [18]:
puan.categories

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [19]:
pd.value_counts(puan)

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
dtype: int64

In [20]:
puan = pd.cut(nt,aralık,right=False)

In [21]:
puan

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [23]:
isim = ["düşük","orta","yüksek","tavan"]
y =pd.cut(nt,aralik,labels=isim)

In [24]:
pd.value_counts(y)

tavan     4
orta      3
yüksek    3
düşük     2
dtype: int64

In [26]:
z = pd.cut(nt,10)
z

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [27]:
pd.value_counts(z)

(58.0, 65.0]     2
(79.0, 86.0]     2
(93.0, 100.0]    2
(29.93, 37.0]    1
(37.0, 44.0]     1
(44.0, 51.0]     1
(51.0, 58.0]     1
(72.0, 79.0]     1
(86.0, 93.0]     1
(65.0, 72.0]     0
dtype: int64

In [39]:
veri = np.random.randn(100)

In [49]:
x = pd.qcut(veri, 4)
pd.value_counts(x)

(-2.048, -0.441]    25
(-0.441, 0.128]     25
(0.128, 0.742]      25
(0.742, 3.321]      25
dtype: int64

## Aykırı Değerleri Filtreleme
- Veri seti içerisinde aykırı değer filtreleme işlemi o anki işleme özgüdür. Bunun için numpy kütüphanesinden faydalanılabilir. Örneğin veri seti içerisinde herhangi bir sutun içerisinde bulunan ve mutlak değeri 3'ü geçen verilerin indexleri istenilebilir. Bunun için sutunu bir değişkene alarak numpy ile sorgulama yapılabilir. DataFrame yapısında bir aykırı değer bulmak isteniyorsa numpy sorgusunun sonuna `.any(1)` parametresi verilir.

In [54]:
veri = pd.DataFrame(np.random.randn(1000,4),
                   columns= list("ABCD"))
veri.head()

A         B         C         D
0  2.156318 -0.668622  1.705598 -0.716324
1  0.064728  1.527244 -1.572658  0.992014
2 -0.202738 -0.089130 -1.004544  0.927527
3 -0.416013  0.232896  1.116970  1.305727
4  1.299436 -1.869558 -0.315913 -0.540635

In [55]:
veri.describe()

A            B            C            D
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.061218    -0.036269    -0.025924     0.012577
std       0.995943     1.042609     0.959860     1.034431
min      -3.461283    -3.134308    -3.024642    -3.022796
25%      -0.593698    -0.746015    -0.669554    -0.699099
50%       0.059007    -0.106552    -0.051788    -0.018539
75%       0.775439     0.667362     0.653320     0.684207
max       3.154931     3.395767     3.119578     3.491013

In [58]:
sutun = veri["B"]

In [68]:
sutun[pd.Index((np.abs(sutun)>3))]

67     3.395767
285   -3.134308
566    3.080662
676    3.252238
994    3.085757
997   -3.036999
Name: B, dtype: float64

In [63]:
veri[(np.abs(veri)>3).any(1)]

A         B         C         D
27   3.111942 -0.615489  0.699218  0.677161
67  -0.603292  3.395767  0.214752  1.696738
158  3.128896  0.046571  1.351339  1.172795
185 -3.213754 -0.905977 -0.275957 -0.983815
235  0.715731 -0.473757 -1.073837  3.148162
280 -1.002521 -1.181371  0.393320  3.209726
285 -1.012491 -3.134308 -0.083414 -2.804869
299  0.126779 -2.067042 -3.024642  0.996903
371  0.043365  1.847865  0.010392  3.491013
431  1.192471 -0.499395  0.771451  3.103564
566  0.176473  3.080662 -0.970057  0.988651
671 -1.076786  0.592577  3.119578  1.387761
676  0.922121  3.252238  0.240527 -1.202512
832 -0.242071 -1.365170  0.999007 -3.022796
839  3.154931  0.250270  1.080326 -0.094528
982 -3.461283  1.114299  0.635827  0.638828
994  1.700133  3.085757  0.927249 -1.011746
997 -1.469265 -3.036999  0.755782  0.848108

In [61]:
np.sign(veri).head()

A    B    C    D
0  1.0 -1.0  1.0 -1.0
1  1.0  1.0 -1.0  1.0
2 -1.0 -1.0 -1.0  1.0
3 -1.0  1.0  1.0  1.0
4  1.0 -1.0 -1.0 -1.0

## Rasgele Satır Sıralama ve Seçme
- Hazırdaki veri setinin tekrar belirli veya rasgele indexlemek istersek `.take()` metotu kullanılır.
- Rasgele bir veya birden fazla satır seçmek istersek `.sample()` metotu kullanılır. Metot tek başına kullanıldığında tek bir satırı verecektir. Birden fazla satır almak için `n=<istenilen_satir_sayisi>` parametresi verilir.

In [71]:
veriSet = pd.DataFrame(np.arange(12).reshape(4,3))
veriSet

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [72]:
yeniSira = np.random.permutation(4)
yeniSira

array([1, 3, 2, 0])

In [81]:
veriSet = veriSet.take(yeniSira)
veriSet

0   1   2
3  9  10  11
0  0   1   2
2  6   7   8
1  3   4   5

In [84]:
veriSet.sample(n=3)

0   1   2
2  6   7   8
0  0   1   2
3  9  10  11

## Dummy Dönüşüme

In [85]:
veri = pd.DataFrame({
    "Harf":["c","b","a","b","b","a"],
    "Sayi":range(6)
})
veri

Harf  Sayi
0    c     0
1    b     1
2    a     2
3    b     3
4    b     4
5    a     5

In [86]:
pd.get_dummies(veri["Harf"])

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [87]:
veri = np.random.randn(10)
veri

array([-0.24221164,  0.16997975,  1.02551772,  1.81281834, -0.51883516,
        0.45665531, -2.43527135,  0.46365378, -0.80011963, -1.17182386])

In [89]:
 pd.get_dummies(pd.cut(veri,4,right=False))

[-2.435, -1.373)  [-1.373, -0.311)  [-0.311, 0.751)  [0.751, 1.817)
0                 0                 0                1               0
1                 0                 0                1               0
2                 0                 0                0               1
3                 0                 0                0               1
4                 0                 1                0               0
5                 0                 0                1               0
6                 1                 0                0               0
7                 0                 0                1               0
8                 0                 1                0               0
9                 0                 1                0               0